# Generated by Django 2.0 on 2018-02-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фоновый рисунок в хедере')),
                ('header_text', models.TextField(max_length=1000, verbose_name='Текст в хедере')),
                ('btn_learn', models.CharField(max_length=50, verbose_name='Кнопка учиться')),
                ('btn_presentation', models.CharField(max_length=50, verbose_name='Кнопка презентация')),
                ('link_presentation', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ccылка на презентацию')),
            ],
            options={
                'verbose_name': 'Конфигурация хедера',
            },
        ),
    ]
