# Generated by Django 2.0 on 2018-02-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_whywe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextWhyWe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Дополнительный текст для блока "почему мы"')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
