# Generated by Django 2.0 on 2018-02-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_textwhywe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Название сайта(title)'},
        ),
        migrations.AlterModelOptions(
            name='textwhywe',
            options={'verbose_name': 'Дополнительный текст для блока почему мы'},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
    ]
