# Generated by Django 2.0 on 2018-02-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20180216_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whywe',
            options={'verbose_name': 'Пиктограмма блока "почему мы"', 'verbose_name_plural': 'Пиктограммы блока "почему мы"'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Иконка'),
        ),
    ]
