# Generated by Django 2.0 on 2018-02-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_configcontactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigContactForm',
        ),
    ]
