# Generated by Django 2.0 on 2018-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_delete_configcontactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockForStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=700, verbose_name='Текст для студентов')),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка для студентов')),
            ],
            options={
                'verbose_name': 'Блок для студентов',
            },
        ),
    ]
