# Generated by Django 2.0 on 2018-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_blockforstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Лого партнеров')),
            ],
            options={
                'verbose_name_plural': 'Лого партнеров',
                'verbose_name': 'Лого партнера',
            },
        ),
    ]
