# Generated by Django 2.0 on 2018-02-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skype', models.CharField(max_length=30, verbose_name='Наш скайп')),
                ('mail', models.CharField(max_length=30, verbose_name='Наш mail')),
                ('first_phone', models.CharField(max_length=30, verbose_name='Первый номер')),
                ('second_phone', models.CharField(max_length=30, verbose_name='Второй номер')),
            ],
            options={
                'verbose_name': 'Настройки хедера',
            },
        ),
    ]
