# Generated by Django 2.0 on 2018-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_configfooter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configfooter',
            options={'verbose_name': 'Настройки футера'},
        ),
        migrations.AddField(
            model_name='configfooter',
            name='copyright',
            field=models.CharField(default='&copy; All rights reserved.', max_length=60, verbose_name='Копирайт'),
        ),
        migrations.AlterField(
            model_name='blockforstudents',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='Картинка для студентов'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='Лого партнеров'),
        ),
    ]
