# Generated by Django 2.0 on 2018-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20180227_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularсourses',
            name='four_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Четвертый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='three_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Третий популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='two_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй популярный'),
        ),
        migrations.AlterField(
            model_name='popularсourses',
            name='first_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Первый популярный'),
        ),
    ]
