# Generated by Django 2.0 on 2018-03-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_auto_20180227_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='btn_learn_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка учиться'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_learn_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка учиться'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_presentation_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка презентация'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_presentation_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка презентация'),
        ),
        migrations.AddField(
            model_name='header',
            name='header_text_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Текст в хедере'),
        ),
        migrations.AddField(
            model_name='header',
            name='header_text_uk',
            field=models.TextField(max_length=1000, null=True, verbose_name='Текст в хедере'),
        ),
        migrations.AddField(
            model_name='header',
            name='link_presentation_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ccылка на презентацию'),
        ),
        migrations.AddField(
            model_name='header',
            name='link_presentation_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ccылка на презентацию'),
        ),
    ]
