# Generated by Django 2.0 on 2018-03-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20180313_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='link_presentation_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='link_presentation_uk',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Имя сайта', max_length=255),
        ),
    ]
