# Generated by Django 2.0 on 2018-03-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_auto_20180313_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='TeamFactory', max_length=255, verbose_name='Имя сайта'),
        ),
    ]
