# Generated by Django 2.0.2 on 2018-03-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_auto_20180313_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='btn_learn_uk',
            new_name='btn_learn_ua',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='btn_presentation_uk',
            new_name='btn_presentation_ua',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='header_text_uk',
            new_name='header_text_ua',
        ),
    ]
