# Generated by Django 2.0.2 on 2018-03-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_auto_20180314_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='whywe',
            name='text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст пиктограммы'),
        ),
        migrations.AddField(
            model_name='whywe',
            name='text_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст пиктограммы'),
        ),
    ]
