# Generated by Django 2.0.2 on 2018-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20180315_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwhywe',
            name='text_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Дополнительный текст для блока "почему мы"'),
        ),
        migrations.AddField(
            model_name='textwhywe',
            name='text_ua',
            field=models.TextField(max_length=500, null=True, verbose_name='Дополнительный текст для блока "почему мы"'),
        ),
    ]
