# Generated by Django 2.0.2 on 2018-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_auto_20180315_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockforstudents',
            name='text_ru',
            field=models.TextField(max_length=700, null=True, verbose_name='Текст для студентов'),
        ),
        migrations.AddField(
            model_name='blockforstudents',
            name='text_ua',
            field=models.TextField(max_length=700, null=True, verbose_name='Текст для студентов'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='first_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Первый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='first_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Первый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='four_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Четвертый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='four_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Четвертый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='three_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Третий популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='three_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Третий популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='two_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='two_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй популярный'),
        ),
    ]
