# Generated by Django 2.0.2 on 2018-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_auto_20180315_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfooter',
            name='copyright_ru',
            field=models.CharField(default='&copy; All rights reserved.', max_length=60, null=True, verbose_name='Копирайт'),
        ),
        migrations.AddField(
            model_name='configfooter',
            name='copyright_ua',
            field=models.CharField(default='&copy; All rights reserved.', max_length=60, null=True, verbose_name='Копирайт'),
        ),
    ]
