# Generated by Django 2.0.2 on 2018-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_auto_20180315_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfooter',
            name='copyright',
            field=models.CharField(default='All rights reserved.', max_length=60, verbose_name='Копирайт'),
        ),
        migrations.AlterField(
            model_name='configfooter',
            name='copyright_ru',
            field=models.CharField(default='All rights reserved.', max_length=60, null=True, verbose_name='Копирайт'),
        ),
        migrations.AlterField(
            model_name='configfooter',
            name='copyright_ua',
            field=models.CharField(default='All rights reserved.', max_length=60, null=True, verbose_name='Копирайт'),
        ),
    ]
