# Generated by Django 2.0.2 on 2018-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_auto_20180316_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockforstudents',
            name='text_ru',
            field=models.TextField(max_length=700, null=True, verbose_name='Текст для студентов'),
        ),
        migrations.AddField(
            model_name='blockforstudents',
            name='text_ua',
            field=models.TextField(max_length=700, null=True, verbose_name='Текст для студентов'),
        ),
        migrations.AddField(
            model_name='configfooter',
            name='copyright_ru',
            field=models.CharField(default='All rights reserved.', max_length=60, null=True, verbose_name='Копирайт'),
        ),
        migrations.AddField(
            model_name='configfooter',
            name='copyright_ua',
            field=models.CharField(default='All rights reserved.', max_length=60, null=True, verbose_name='Копирайт'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_learn_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка учиться'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_learn_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка учиться'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_presentation_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка презентация'),
        ),
        migrations.AddField(
            model_name='header',
            name='btn_presentation_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка презентация'),
        ),
        migrations.AddField(
            model_name='header',
            name='header_text_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Текст в хедере'),
        ),
        migrations.AddField(
            model_name='header',
            name='header_text_ua',
            field=models.TextField(max_length=1000, null=True, verbose_name='Текст в хедере'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='first_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Первый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='first_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Первый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='four_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Четвертый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='four_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Четвертый популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='three_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Третий популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='three_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Третий популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='two_course_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй популярный'),
        ),
        migrations.AddField(
            model_name='popularсourses',
            name='two_course_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй популярный'),
        ),
        migrations.AddField(
            model_name='textwhywe',
            name='text_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Дополнительный текст для блока "почему мы"'),
        ),
        migrations.AddField(
            model_name='textwhywe',
            name='text_ua',
            field=models.TextField(max_length=500, null=True, verbose_name='Дополнительный текст для блока "почему мы"'),
        ),
        migrations.AddField(
            model_name='whywe',
            name='text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст пиктограммы'),
        ),
        migrations.AddField(
            model_name='whywe',
            name='text_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст пиктограммы'),
        ),
    ]
