# Generated by Django 2.0 on 2018-02-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя лектора')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия лектора')),
                ('position', models.CharField(max_length=200, verbose_name='Должность лектора')),
            ],
            options={
                'verbose_name_plural': 'Лекторы',
                'verbose_name': 'Лектор',
            },
        ),
    ]
