# Generated by Django 2.0 on 2018-02-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема лекции')),
                ('where', models.CharField(default='г.Киев ул. Соломенская 3', max_length=100, verbose_name='Где')),
                ('when', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('description', models.TextField(max_length=1000, verbose_name='Текст ивента')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Lector', verbose_name='Выберите лектора')),
            ],
            options={
                'verbose_name_plural': 'Ивенты',
                'verbose_name': 'Ивент',
            },
        ),
    ]
