# Generated by Django 2.0 on 2018-02-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEventsPopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_where', models.CharField(default='Где', max_length=20, verbose_name='Блок где')),
                ('text_when', models.CharField(default='Когда', max_length=20, verbose_name='Блок Когда')),
                ('text_lector', models.CharField(default='Автор', max_length=20, verbose_name='Блок автора')),
                ('name_form', models.CharField(max_length=20, verbose_name='Название формы')),
                ('text_form', models.CharField(max_length=20, verbose_name='Вспомогательный текст в форме')),
                ('btn', models.CharField(max_length=15, verbose_name='Кнопка в форме')),
            ],
            options={
                'verbose_name': 'Настройка модального окна Ивента ',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Lector', verbose_name='лектор'),
        ),
    ]
