# Generated by Django 2.0 on 2018-02-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180221_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_client', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'verbose_name': 'Регистрации на ивент',
            },
        ),
    ]
