# Generated by Django 2.0 on 2018-02-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180221_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
