# Generated by Django 2.0.2 on 2018-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Текст ивента'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ua',
            field=models.TextField(max_length=1000, null=True, verbose_name='Текст ивента'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тема лекции'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Тема лекции'),
        ),
        migrations.AddField(
            model_name='event',
            name='where_ru',
            field=models.CharField(default='г.Киев ул. Соломенская 3', max_length=100, null=True, verbose_name='Где'),
        ),
        migrations.AddField(
            model_name='event',
            name='where_ua',
            field=models.CharField(default='г.Киев ул. Соломенская 3', max_length=100, null=True, verbose_name='Где'),
        ),
        migrations.AddField(
            model_name='lector',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя лектора'),
        ),
        migrations.AddField(
            model_name='lector',
            name='name_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя лектора'),
        ),
        migrations.AddField(
            model_name='lector',
            name='position_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность лектора'),
        ),
        migrations.AddField(
            model_name='lector',
            name='position_ua',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность лектора'),
        ),
        migrations.AddField(
            model_name='lector',
            name='surname_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия лектора'),
        ),
        migrations.AddField(
            model_name='lector',
            name='surname_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия лектора'),
        ),
    ]
