# Generated by Django 2.0.2 on 2018-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180315_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationeventspopup',
            name='btn_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='Кнопка в форме'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='btn_ua',
            field=models.CharField(max_length=15, null=True, verbose_name='Кнопка в форме'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='name_form_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Название формы'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='name_form_ua',
            field=models.CharField(max_length=20, null=True, verbose_name='Название формы'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_form_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Вспомогательный текст в форме'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_form_ua',
            field=models.CharField(max_length=20, null=True, verbose_name='Вспомогательный текст в форме'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_lector_ru',
            field=models.CharField(default='Автор', max_length=20, null=True, verbose_name='Блок автора'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_lector_ua',
            field=models.CharField(default='Автор', max_length=20, null=True, verbose_name='Блок автора'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_when_ru',
            field=models.CharField(default='Когда', max_length=20, null=True, verbose_name='Блок Когда'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_when_ua',
            field=models.CharField(default='Когда', max_length=20, null=True, verbose_name='Блок Когда'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_where_ru',
            field=models.CharField(default='Где', max_length=20, null=True, verbose_name='Блок где'),
        ),
        migrations.AddField(
            model_name='configurationeventspopup',
            name='text_where_ua',
            field=models.CharField(default='Где', max_length=20, null=True, verbose_name='Блок где'),
        ),
    ]
