# Generated by Django 2.0.2 on 2018-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180315_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='btn',
            field=models.CharField(max_length=30, verbose_name='Кнопка в форме'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='btn_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Кнопка в форме'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='btn_ua',
            field=models.CharField(max_length=30, null=True, verbose_name='Кнопка в форме'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='name_form',
            field=models.CharField(max_length=100, verbose_name='Название формы'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='name_form_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название формы'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='name_form_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Название формы'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_form',
            field=models.CharField(max_length=100, verbose_name='Вспомогательный текст в форме'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_form_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Вспомогательный текст в форме'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_form_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Вспомогательный текст в форме'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_lector',
            field=models.CharField(default='Автор', max_length=100, verbose_name='Блок автора'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_lector_ru',
            field=models.CharField(default='Автор', max_length=100, null=True, verbose_name='Блок автора'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_lector_ua',
            field=models.CharField(default='Автор', max_length=100, null=True, verbose_name='Блок автора'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_when',
            field=models.CharField(default='Когда', max_length=100, verbose_name='Блок Когда'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_when_ru',
            field=models.CharField(default='Когда', max_length=100, null=True, verbose_name='Блок Когда'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_when_ua',
            field=models.CharField(default='Когда', max_length=100, null=True, verbose_name='Блок Когда'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_where',
            field=models.CharField(default='Где', max_length=100, verbose_name='Блок где'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_where_ru',
            field=models.CharField(default='Где', max_length=100, null=True, verbose_name='Блок где'),
        ),
        migrations.AlterField(
            model_name='configurationeventspopup',
            name='text_where_ua',
            field=models.CharField(default='Где', max_length=100, null=True, verbose_name='Блок где'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Текст ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=models.TextField(max_length=3000, null=True, verbose_name='Текст ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ua',
            field=models.TextField(max_length=3000, null=True, verbose_name='Текст ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(max_length=500, verbose_name='Тема лекции'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Тема лекции'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme_ua',
            field=models.CharField(max_length=500, null=True, verbose_name='Тема лекции'),
        ),
    ]
