# Generated by Django 2.0 on 2018-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='СonsultationPopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Напишите нам', max_length=50, verbose_name='Текст заголовка окна')),
                ('type_relation', models.CharField(default='Напишите нам', max_length=50, verbose_name='Email или номер телефона')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
