# Generated by Django 2.0 on 2018-02-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180216_2132'),
        ('popup', '0002_auto_20180217_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Введите ваше имя')),
                ('mail', models.URLField(verbose_name='Введите вашу почту')),
                ('phone', models.CharField(max_length=15, verbose_name='Введите ваш телефон')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
