# Generated by Django 2.0 on 2018-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0004_auto_20180217_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Введите вашу почту'),
        ),
    ]
