# Generated by Django 2.0 on 2018-02-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0006_auto_20180217_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=35, verbose_name='Введите ваш телефон'),
        ),
    ]
