# Generated by Django 2.0 on 2018-02-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180216_2132'),
        ('popup', '0007_auto_20180217_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефонный номер')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Регистрация на курсе',
                'verbose_name_plural': 'Регистрации на курс',
            },
        ),
    ]
