# Generated by Django 2.0 on 2018-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0012_auto_20180220_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpErrorRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст "Ошибка при регистрации"')),
            ],
            options={
                'verbose_name': 'Текст "Ошибка при регистрации"',
            },
        ),
        migrations.CreateModel(
            name='PopUpThanksConsulting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст "Окно после заказа консультации"')),
            ],
            options={
                'verbose_name': 'Текст "Окно после заказа консультации"',
            },
        ),
        migrations.CreateModel(
            name='PopUpThanksRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст "Окно после регистрации"')),
            ],
            options={
                'verbose_name': 'Текст "Окно после заказа регистрации"',
            },
        ),
    ]
