# Generated by Django 2.0 on 2018-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0013_popuperrorregister_popupthanksconsulting_popupthanksregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpThanksEventRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Tекст модального окна "спасибо за регистрацию"',
            },
        ),
    ]
