# Generated by Django 2.0 on 2018-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0014_popupthankseventregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupthankseventregister',
            options={'verbose_name': 'Tекст модального окна "спасибо за регистрацию на ивент"'},
        ),
    ]
