# Generated by Django 2.0 on 2018-02-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0016_configheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigHeader',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Запись на консультацию', 'verbose_name_plural': 'Записи на консультации'},
        ),
    ]
