# Generated by Django 2.0.2 on 2018-03-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0019_auto_20180315_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='configregistrationform',
            name='button_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка отправки'),
        ),
        migrations.AddField(
            model_name='configregistrationform',
            name='button_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Кнопка отправки'),
        ),
        migrations.AddField(
            model_name='configregistrationform',
            name='header_ru',
            field=models.CharField(default='Заказать консультацию', max_length=50, null=True, verbose_name='Заголовок модального окна'),
        ),
        migrations.AddField(
            model_name='configregistrationform',
            name='header_ua',
            field=models.CharField(default='Заказать консультацию', max_length=50, null=True, verbose_name='Заголовок модального окна'),
        ),
        migrations.AddField(
            model_name='configregistrationform',
            name='text_ru',
            field=models.TextField(max_length=200, null=True, verbose_name='Вспомогательный текст'),
        ),
        migrations.AddField(
            model_name='configregistrationform',
            name='text_ua',
            field=models.TextField(max_length=200, null=True, verbose_name='Вспомогательный текст'),
        ),
    ]
