# Generated by Django 2.0 on 2018-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия автора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фото автора')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
                'verbose_name': 'Автор',
            },
        ),
    ]
