# Generated by Django 2.0 on 2018-02-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название курса на русском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название курса на английском')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание курса')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность курса')),
                ('start_course', models.DateField(verbose_name='Старт курса')),
                ('end_course', models.DateField(verbose_name='Конец курса')),
                ('background', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фоновая картинка')),
                ('shedule_btn_text', models.CharField(max_length=100, verbose_name=' Текст кнопки расписания')),
                ('upload', models.FileField(upload_to='uploads/', verbose_name='Припрепить файл с расаписанием')),
                ('learn_btn_text', models.CharField(max_length=100, verbose_name='Текст кнопки учиться')),
                ('number_of_seats', models.IntegerField(default=50, verbose_name='Количество мест на курс')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Author', verbose_name='Выберите автора')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'verbose_name': 'Курс',
            },
        ),
    ]
