# Generated by Django 2.0 on 2018-02-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='shedule_btn_text',
            field=models.CharField(default='Расписание', max_length=100, verbose_name=' Текст кнопки расписания'),
        ),
    ]
