# Generated by Django 2.0 on 2018-02-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180216_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_btn_text',
            field=models.CharField(default='Учиться', max_length=100, verbose_name='Текст кнопки учиться'),
        ),
    ]
