# Generated by Django 2.0 on 2018-02-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180220_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=50, verbose_name='Количество мест на курс'),
        ),
    ]
