# Generated by Django 2.0.2 on 2018-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180222_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='author',
            name='position_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='author',
            name='position_ua',
            field=models.CharField(max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='author',
            name='surname_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия автора'),
        ),
        migrations.AddField(
            model_name='author',
            name='surname_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия автора'),
        ),
    ]
