# Generated by Django 2.0.2 on 2018-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180315_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ua',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Длительность курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Длительность курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_btn_text_ru',
            field=models.CharField(default='Записаться', max_length=100, null=True, verbose_name='Текст кнопки учиться'),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_btn_text_ua',
            field=models.CharField(default='Записаться', max_length=100, null=True, verbose_name='Текст кнопки учиться'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название курса на русском'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Название курса на русском'),
        ),
        migrations.AddField(
            model_name='course',
            name='shedule_btn_text_ru',
            field=models.CharField(default='Расписание', max_length=100, null=True, verbose_name=' Текст кнопки расписания'),
        ),
        migrations.AddField(
            model_name='course',
            name='shedule_btn_text_ua',
            field=models.CharField(default='Расписание', max_length=100, null=True, verbose_name=' Текст кнопки расписания'),
        ),
    ]
